//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACM.Service.Client.AdServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdServiceRef.IAdService")]
    public interface IAdService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetAdRestrictionCategory", ReplyAction="http://tempuri.org/IAdService/GetAdRestrictionCategoryResponse")]
        ACM.Model.CustomModel.Restrictions GetAdRestrictionCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetAdRestrictionCategory", ReplyAction="http://tempuri.org/IAdService/GetAdRestrictionCategoryResponse")]
        System.Threading.Tasks.Task<ACM.Model.CustomModel.Restrictions> GetAdRestrictionCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetOutstandingTask", ReplyAction="http://tempuri.org/IAdService/GetOutstandingTaskResponse")]
        System.Collections.Generic.List<ACM.Model.AdOutStandingTask> GetOutstandingTask(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetOutstandingTask", ReplyAction="http://tempuri.org/IAdService/GetOutstandingTaskResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ACM.Model.AdOutStandingTask>> GetOutstandingTaskAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdInfo", ReplyAction="http://tempuri.org/IAdService/AdInfoResponse")]
        System.Collections.Generic.List<ACM.Model.Ad> AdInfo(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdInfo", ReplyAction="http://tempuri.org/IAdService/AdInfoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ACM.Model.Ad>> AdInfoAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdInq", ReplyAction="http://tempuri.org/IAdService/AdInqResponse")]
        ACM.Model.Ad AdInq(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdInq", ReplyAction="http://tempuri.org/IAdService/AdInqResponse")]
        System.Threading.Tasks.Task<ACM.Model.Ad> AdInqAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdAdd", ReplyAction="http://tempuri.org/IAdService/AdAddResponse")]
        ACM.Model.Ad AdAdd(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdAdd", ReplyAction="http://tempuri.org/IAdService/AdAddResponse")]
        System.Threading.Tasks.Task<ACM.Model.Ad> AdAddAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdMod", ReplyAction="http://tempuri.org/IAdService/AdModResponse")]
        string AdMod(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdMod", ReplyAction="http://tempuri.org/IAdService/AdModResponse")]
        System.Threading.Tasks.Task<string> AdModAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdDel", ReplyAction="http://tempuri.org/IAdService/AdDelResponse")]
        string AdDel(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdDel", ReplyAction="http://tempuri.org/IAdService/AdDelResponse")]
        System.Threading.Tasks.Task<string> AdDelAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/UpdateAdRestriction", ReplyAction="http://tempuri.org/IAdService/UpdateAdRestrictionResponse")]
        string UpdateAdRestriction(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/UpdateAdRestriction", ReplyAction="http://tempuri.org/IAdService/UpdateAdRestrictionResponse")]
        System.Threading.Tasks.Task<string> UpdateAdRestrictionAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdLocationsByCampaign", ReplyAction="http://tempuri.org/IAdService/AdLocationsByCampaignResponse")]
        System.Collections.Generic.List<ACM.Model.CustomModel.AdlocationList> AdLocationsByCampaign(int campaignId, int adid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdLocationsByCampaign", ReplyAction="http://tempuri.org/IAdService/AdLocationsByCampaignResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ACM.Model.CustomModel.AdlocationList>> AdLocationsByCampaignAsync(int campaignId, int adid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/CheckMediaFileTypes", ReplyAction="http://tempuri.org/IAdService/CheckMediaFileTypesResponse")]
        System.Collections.Generic.Dictionary<string, string> CheckMediaFileTypes(string AdlocationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/CheckMediaFileTypes", ReplyAction="http://tempuri.org/IAdService/CheckMediaFileTypesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> CheckMediaFileTypesAsync(string AdlocationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdsByCampaign", ReplyAction="http://tempuri.org/IAdService/AdsByCampaignResponse")]
        System.Collections.Generic.List<ACM.Model.CustomModel.AdInfo_Result> AdsByCampaign(int campaignId, int deploymentPeriodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdsByCampaign", ReplyAction="http://tempuri.org/IAdService/AdsByCampaignResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ACM.Model.CustomModel.AdInfo_Result>> AdsByCampaignAsync(int campaignId, int deploymentPeriodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetAdRestrictionFlag", ReplyAction="http://tempuri.org/IAdService/GetAdRestrictionFlagResponse")]
        System.Collections.Generic.Dictionary<int, int> GetAdRestrictionFlag(int campaignId, int adid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetAdRestrictionFlag", ReplyAction="http://tempuri.org/IAdService/GetAdRestrictionFlagResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, int>> GetAdRestrictionFlagAsync(int campaignId, int adid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdAdRestrictionFlagAdd", ReplyAction="http://tempuri.org/IAdService/AdAdRestrictionFlagAddResponse")]
        string AdAdRestrictionFlagAdd(ACM.Model.Ad ad, System.Collections.Generic.List<int> flags, bool applyAll);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdAdRestrictionFlagAdd", ReplyAction="http://tempuri.org/IAdService/AdAdRestrictionFlagAddResponse")]
        System.Threading.Tasks.Task<string> AdAdRestrictionFlagAddAsync(ACM.Model.Ad ad, System.Collections.Generic.List<int> flags, bool applyAll);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdInfoInq", ReplyAction="http://tempuri.org/IAdService/AdInfoInqResponse")]
        ACM.Model.CustomModel.AdInfo AdInfoInq(int campaignId, int adid, int deploymentPeriodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdInfoInq", ReplyAction="http://tempuri.org/IAdService/AdInfoInqResponse")]
        System.Threading.Tasks.Task<ACM.Model.CustomModel.AdInfo> AdInfoInqAsync(int campaignId, int adid, int deploymentPeriodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdStatusModify", ReplyAction="http://tempuri.org/IAdService/AdStatusModifyResponse")]
        string AdStatusModify(ACM.Model.AdDeploymentPeriod request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdStatusModify", ReplyAction="http://tempuri.org/IAdService/AdStatusModifyResponse")]
        System.Threading.Tasks.Task<string> AdStatusModifyAsync(ACM.Model.AdDeploymentPeriod request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdStatusInquiry", ReplyAction="http://tempuri.org/IAdService/AdStatusInquiryResponse")]
        ACM.Model.AdDeploymentPeriod AdStatusInquiry(ACM.Model.AdDeploymentPeriod request, int deploymentPeriodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdStatusInquiry", ReplyAction="http://tempuri.org/IAdService/AdStatusInquiryResponse")]
        System.Threading.Tasks.Task<ACM.Model.AdDeploymentPeriod> AdStatusInquiryAsync(ACM.Model.AdDeploymentPeriod request, int deploymentPeriodId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdServiceChannel : ACM.Service.Client.AdServiceRef.IAdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdServiceClient : System.ServiceModel.ClientBase<ACM.Service.Client.AdServiceRef.IAdService>, ACM.Service.Client.AdServiceRef.IAdService {
        
        public AdServiceClient() {
        }
        
        public AdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ACM.Model.CustomModel.Restrictions GetAdRestrictionCategory() {
            return base.Channel.GetAdRestrictionCategory();
        }
        
        public System.Threading.Tasks.Task<ACM.Model.CustomModel.Restrictions> GetAdRestrictionCategoryAsync() {
            return base.Channel.GetAdRestrictionCategoryAsync();
        }
        
        public System.Collections.Generic.List<ACM.Model.AdOutStandingTask> GetOutstandingTask(ACM.Model.Ad request) {
            return base.Channel.GetOutstandingTask(request);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ACM.Model.AdOutStandingTask>> GetOutstandingTaskAsync(ACM.Model.Ad request) {
            return base.Channel.GetOutstandingTaskAsync(request);
        }
        
        public System.Collections.Generic.List<ACM.Model.Ad> AdInfo(ACM.Model.Ad request) {
            return base.Channel.AdInfo(request);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ACM.Model.Ad>> AdInfoAsync(ACM.Model.Ad request) {
            return base.Channel.AdInfoAsync(request);
        }
        
        public ACM.Model.Ad AdInq(ACM.Model.Ad request) {
            return base.Channel.AdInq(request);
        }
        
        public System.Threading.Tasks.Task<ACM.Model.Ad> AdInqAsync(ACM.Model.Ad request) {
            return base.Channel.AdInqAsync(request);
        }
        
        public ACM.Model.Ad AdAdd(ACM.Model.Ad request) {
            return base.Channel.AdAdd(request);
        }
        
        public System.Threading.Tasks.Task<ACM.Model.Ad> AdAddAsync(ACM.Model.Ad request) {
            return base.Channel.AdAddAsync(request);
        }
        
        public string AdMod(ACM.Model.Ad request) {
            return base.Channel.AdMod(request);
        }
        
        public System.Threading.Tasks.Task<string> AdModAsync(ACM.Model.Ad request) {
            return base.Channel.AdModAsync(request);
        }
        
        public string AdDel(ACM.Model.Ad request) {
            return base.Channel.AdDel(request);
        }
        
        public System.Threading.Tasks.Task<string> AdDelAsync(ACM.Model.Ad request) {
            return base.Channel.AdDelAsync(request);
        }
        
        public string UpdateAdRestriction(ACM.Model.Ad request) {
            return base.Channel.UpdateAdRestriction(request);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAdRestrictionAsync(ACM.Model.Ad request) {
            return base.Channel.UpdateAdRestrictionAsync(request);
        }
        
        public System.Collections.Generic.List<ACM.Model.CustomModel.AdlocationList> AdLocationsByCampaign(int campaignId, int adid) {
            return base.Channel.AdLocationsByCampaign(campaignId, adid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ACM.Model.CustomModel.AdlocationList>> AdLocationsByCampaignAsync(int campaignId, int adid) {
            return base.Channel.AdLocationsByCampaignAsync(campaignId, adid);
        }
        
        public System.Collections.Generic.Dictionary<string, string> CheckMediaFileTypes(string AdlocationCode) {
            return base.Channel.CheckMediaFileTypes(AdlocationCode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> CheckMediaFileTypesAsync(string AdlocationCode) {
            return base.Channel.CheckMediaFileTypesAsync(AdlocationCode);
        }
        
        public System.Collections.Generic.List<ACM.Model.CustomModel.AdInfo_Result> AdsByCampaign(int campaignId, int deploymentPeriodId) {
            return base.Channel.AdsByCampaign(campaignId, deploymentPeriodId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ACM.Model.CustomModel.AdInfo_Result>> AdsByCampaignAsync(int campaignId, int deploymentPeriodId) {
            return base.Channel.AdsByCampaignAsync(campaignId, deploymentPeriodId);
        }
        
        public System.Collections.Generic.Dictionary<int, int> GetAdRestrictionFlag(int campaignId, int adid) {
            return base.Channel.GetAdRestrictionFlag(campaignId, adid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, int>> GetAdRestrictionFlagAsync(int campaignId, int adid) {
            return base.Channel.GetAdRestrictionFlagAsync(campaignId, adid);
        }
        
        public string AdAdRestrictionFlagAdd(ACM.Model.Ad ad, System.Collections.Generic.List<int> flags, bool applyAll) {
            return base.Channel.AdAdRestrictionFlagAdd(ad, flags, applyAll);
        }
        
        public System.Threading.Tasks.Task<string> AdAdRestrictionFlagAddAsync(ACM.Model.Ad ad, System.Collections.Generic.List<int> flags, bool applyAll) {
            return base.Channel.AdAdRestrictionFlagAddAsync(ad, flags, applyAll);
        }
        
        public ACM.Model.CustomModel.AdInfo AdInfoInq(int campaignId, int adid, int deploymentPeriodId) {
            return base.Channel.AdInfoInq(campaignId, adid, deploymentPeriodId);
        }
        
        public System.Threading.Tasks.Task<ACM.Model.CustomModel.AdInfo> AdInfoInqAsync(int campaignId, int adid, int deploymentPeriodId) {
            return base.Channel.AdInfoInqAsync(campaignId, adid, deploymentPeriodId);
        }
        
        public string AdStatusModify(ACM.Model.AdDeploymentPeriod request) {
            return base.Channel.AdStatusModify(request);
        }
        
        public System.Threading.Tasks.Task<string> AdStatusModifyAsync(ACM.Model.AdDeploymentPeriod request) {
            return base.Channel.AdStatusModifyAsync(request);
        }
        
        public ACM.Model.AdDeploymentPeriod AdStatusInquiry(ACM.Model.AdDeploymentPeriod request, int deploymentPeriodId) {
            return base.Channel.AdStatusInquiry(request, deploymentPeriodId);
        }
        
        public System.Threading.Tasks.Task<ACM.Model.AdDeploymentPeriod> AdStatusInquiryAsync(ACM.Model.AdDeploymentPeriod request, int deploymentPeriodId) {
            return base.Channel.AdStatusInquiryAsync(request, deploymentPeriodId);
        }
    }
}
