//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACM.AdServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdServiceRef.IAdService")]
    public interface IAdService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetAdRestrictionCategory", ReplyAction="http://tempuri.org/IAdService/GetAdRestrictionCategoryResponse")]
        ACM.Model.CustomModel.Restrictions GetAdRestrictionCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetAdRestrictionCategory", ReplyAction="http://tempuri.org/IAdService/GetAdRestrictionCategoryResponse")]
        System.Threading.Tasks.Task<ACM.Model.CustomModel.Restrictions> GetAdRestrictionCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetOutstandingTask", ReplyAction="http://tempuri.org/IAdService/GetOutstandingTaskResponse")]
        ACM.Model.AdOutStandingTask[] GetOutstandingTask(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/GetOutstandingTask", ReplyAction="http://tempuri.org/IAdService/GetOutstandingTaskResponse")]
        System.Threading.Tasks.Task<ACM.Model.AdOutStandingTask[]> GetOutstandingTaskAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdInfo", ReplyAction="http://tempuri.org/IAdService/AdInfoResponse")]
        ACM.Model.Ad[] AdInfo(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdInfo", ReplyAction="http://tempuri.org/IAdService/AdInfoResponse")]
        System.Threading.Tasks.Task<ACM.Model.Ad[]> AdInfoAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdInq", ReplyAction="http://tempuri.org/IAdService/AdInqResponse")]
        ACM.Model.Ad AdInq(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdInq", ReplyAction="http://tempuri.org/IAdService/AdInqResponse")]
        System.Threading.Tasks.Task<ACM.Model.Ad> AdInqAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdAdd", ReplyAction="http://tempuri.org/IAdService/AdAddResponse")]
        string AdAdd(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdAdd", ReplyAction="http://tempuri.org/IAdService/AdAddResponse")]
        System.Threading.Tasks.Task<string> AdAddAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdMod", ReplyAction="http://tempuri.org/IAdService/AdModResponse")]
        string AdMod(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdMod", ReplyAction="http://tempuri.org/IAdService/AdModResponse")]
        System.Threading.Tasks.Task<string> AdModAsync(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdDel", ReplyAction="http://tempuri.org/IAdService/AdDelResponse")]
        string AdDel(ACM.Model.Ad request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdService/AdDel", ReplyAction="http://tempuri.org/IAdService/AdDelResponse")]
        System.Threading.Tasks.Task<string> AdDelAsync(ACM.Model.Ad request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdServiceChannel : ACM.AdServiceRef.IAdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdServiceClient : System.ServiceModel.ClientBase<ACM.AdServiceRef.IAdService>, ACM.AdServiceRef.IAdService {
        
        public AdServiceClient() {
        }
        
        public AdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ACM.Model.CustomModel.Restrictions GetAdRestrictionCategory() {
            return base.Channel.GetAdRestrictionCategory();
        }
        
        public System.Threading.Tasks.Task<ACM.Model.CustomModel.Restrictions> GetAdRestrictionCategoryAsync() {
            return base.Channel.GetAdRestrictionCategoryAsync();
        }
        
        public ACM.Model.AdOutStandingTask[] GetOutstandingTask(ACM.Model.Ad request) {
            return base.Channel.GetOutstandingTask(request);
        }
        
        public System.Threading.Tasks.Task<ACM.Model.AdOutStandingTask[]> GetOutstandingTaskAsync(ACM.Model.Ad request) {
            return base.Channel.GetOutstandingTaskAsync(request);
        }
        
        public ACM.Model.Ad[] AdInfo(ACM.Model.Ad request) {
            return base.Channel.AdInfo(request);
        }
        
        public System.Threading.Tasks.Task<ACM.Model.Ad[]> AdInfoAsync(ACM.Model.Ad request) {
            return base.Channel.AdInfoAsync(request);
        }
        
        public ACM.Model.Ad AdInq(ACM.Model.Ad request) {
            return base.Channel.AdInq(request);
        }
        
        public System.Threading.Tasks.Task<ACM.Model.Ad> AdInqAsync(ACM.Model.Ad request) {
            return base.Channel.AdInqAsync(request);
        }
        
        public string AdAdd(ACM.Model.Ad request) {
            return base.Channel.AdAdd(request);
        }
        
        public System.Threading.Tasks.Task<string> AdAddAsync(ACM.Model.Ad request) {
            return base.Channel.AdAddAsync(request);
        }
        
        public string AdMod(ACM.Model.Ad request) {
            return base.Channel.AdMod(request);
        }
        
        public System.Threading.Tasks.Task<string> AdModAsync(ACM.Model.Ad request) {
            return base.Channel.AdModAsync(request);
        }
        
        public string AdDel(ACM.Model.Ad request) {
            return base.Channel.AdDel(request);
        }
        
        public System.Threading.Tasks.Task<string> AdDelAsync(ACM.Model.Ad request) {
            return base.Channel.AdDelAsync(request);
        }
    }
}
